# action.yml
name: 'NPM Tests'
description: 'Run npm tests'
outputs:
  time:
    description: 'The time'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-square'
  color: 'orange'
